### ISSUE TITLE
Optional ViewModel

### ISSUE THREAD

**Issue by RobHudson72** [michaelscodingspot/WPF_MVVMC#10]
Question...

The documentation states that the ViewModel is optional, and that if one exists, then the DataContext is set to the ViewModel.  

Does this mean that if you omit the ViewModel, then you can bind the view directly to the controller?  If so, is there a simple code sample that demonstrates that?

**Comment by michaelscodingspot** [comment]
Hi,

The View never binds to the controller. If you omit the View, the DataContext is null.

**Comment by RobHudson72** [comment]
Understood, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
