### ISSUE TITLE
if view and viewcontroller and ViewModel have own folder, how to binding path

### ISSUE THREAD

**Issue by tugodxx** [michaelscodingspot/WPF_MVVMC#11]
if view and viewcontroller and ViewModel have own folder, how to binding path.
I don't create view and viewcontroller and ViewModel in same path. how to use navigation?

**Comment by michaelscodingspot** [comment]
Hi,

The View, ViewModel, and Controller should be in the same namespace.
It's easiest when they are in the same folder because VS will automatically
set the namespace. But they don't have to be in the same folder, you can
manually change their namespace and it will work.
