### ISSUE TITLE
SOLVED: How to get model data from code behind of step?

### ISSUE THREAD

**Issue by papillon2k2** [michaelscodingspot/WPF_MVVMC#15]
Hi, thanks for this package. 

How can I access the model from the code behind of one of the steps?
Specifically in the last step, I have a button and I want to get model's data from the button OnClick() event handler.

Thanks

UPDATE - ok sorry, it was simple, I found it, I just updated the viewmodel from the model (in viewmodel's constructor), then accessed the viewmodel from code behind taking it from the controller's DataContext:
            FourthStepViewModel viewModel = this.DataContext as FourthStepViewModel;
            var st = viewModel.something;

Marking the issue as solved.

**Comment by michaelscodingspot** [comment]
All right, I’m glad you solve it.
