### ISSUE TITLE
Dependency Injection for json config file

### ISSUE THREAD

**Issue by papillon2k2** [michaelscodingspot/WPF_MVVMC#16]
I am trying to use an appsettings.json file in my app. I have implemented it the usual way with dependency injection, registering the IConfiguration object and MainWindow in startup.

Then in MainWindow code behind I am able to access configuration values , by injecting the IConfiguration object into MainWindow constructor, like this:

```
    public partial class MainWindow : Window {
        private readonly IConfiguration _config;
        public MainWindow(IConfiguration config) {
            InitializeComponent();
            _config = config;
        }
        public void someMethod() {
            //get config value
            string someConfigValue = _config.GetValue<string>("something");
        }
    }
```

But How could I inject it into each Step View, so I can access it from each step view code-behind? is this possible? I guess I would need to inject it first into the Controller constructor, but have not been able to make it work (apparently the package code always calls the empty constructor, not the one with the IConfiguration object injected...)

**Comment by michaelscodingspot** [comment]
You're right, MVVMC doesn't support dependency injection  right now.
What dependency injection framework are you using btw?

In any case, here's a suggestion of a relatively easy implementation usage:
* In NavigationService, you will register your instance. Something like `navigationService.ResgisterService(myService, Lifetime.Singleton)`.
* It will be injected in the constructor of Controllers and ViewModels. Not sure about Views.
* If this feature is highly requested, it's possible to create  additional NuGet packages per dep. injection framework. For example, MVVMC.NInject, which will add extension methods to Ninject that don't require you to inject to NavigationService yourself.

What do you think?

**Comment by michaelscodingspot** [comment]
Closing due to lack of interest. Reopen if the need arises.
