### ISSUE TITLE
I am facing the issues in this MVVMC package

### ISSUE THREAD

**Issue by JSGund** [michaelscodingspot/WPF_MVVMC#6]
I am using in .Net Framework 4.7.2, and getting following exception:

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='The invocation of the constructor on type 'MVVMC.Region' that matches the specified binding constraints threw an exception.' Line number '20' and line position '10'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

**Comment by michaelscodingspot** [comment]
Hi,

Which Wpf.MVVMC NuGet version are you using?

I was able to create a project with a 4.7.2 framework and the latest Wpf.MVVMC project:
[https://drive.google.com/open?id=1b4Nimeagqoxam08BtQyoYM5A5I0J23cU](https://drive.google.com/open?id=1b4Nimeagqoxam08BtQyoYM5A5I0J23cU)

It seems you have an unrelated problem with Entity Framework Core. Wpf.MVVMC doesn't depend on it.
I also tried adding Microsoft.EntityFrameworkCore to the project, but everything still works.
