### ISSUE TITLE
View and ViewController destructor

### ISSUE THREAD

**Issue by LucaFagan** [michaelscodingspot/WPF_MVVMC#8]
Hi,
when GoBackCommand is invoked are the top view and associated view model destroyed ?

For example, if view1 is initial view and I navigate to view2, when I go back to view1, is view2 destroyed and when ? I have made same tests and destructors are never called.

**Comment by michaelscodingspot** [comment]
Hi,

The history does not save instances, just page names (strings), so when navigating back the initial view is destroyed. Try forcing garbage collection with

```
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();
```

**Comment by LucaFagan** [comment]
Hi, 
you are right, forcing GC destructors are fired.

Thanks for the reply.
