### ISSUE TITLE
Keeping step data when you go back

### ISSUE THREAD

**Issue by LucaFagan** [michaelscodingspot/WPF_MVVMC#9]
Hi,
I had a look at the sample "Add Employee" and I've noticed that when I go to previous step all data are lost. For example if I enter first name, then go to "Last name step" and then go back, the first name field is empty.

What's the proper way to keep entered data ? Using viewBag when I navigate to previous step and set view model fields in Initialize method (*) or is there a better solution ?

(*) _firstName = ((Employee)this.ViewBag["Employee"]).FirstName;

**Comment by michaelscodingspot** [comment]
Hi,

The solution as you suggest is good. 
You can also set our controller's "HistoryMode" to "SaveParameterInstance" and use "NavigationParameter" as the object that holds all the fields. Then, same as with ViewBag, populate the fields in Initialize().

I did think to introduce a new navigation mode "SaveViewModel". In which case, the ViewModel instance will be saved in history and won't be created anew...

**Comment by LucaFagan** [comment]
Hi Michael, 
first of all thanks for the time you spend in replying. SaveViewModel mode would be great.

I've tried the solution of setting "HistoryMode" to "SaveParameterInstance" and when I go back to a view controller its properties "Parameter" and "ViewBack" are populated. So far so good.

Because the use of "SaveParameterInstance" mode, as you have written in documentation, might lead to memory leaks I wanted to experiment the "UseCommandParameter" mode but I don't understand how to pass Parameter and ViewBack when GoBack is called.

I use the following code for GoBack button:

            <Button Command="{mvvmc:GoBackCommand ControllerID='Main', HistoricalNavigationMode=UseCommandParameter}" 
                    Width="100"
                    Margin="5,0"
                    Content="Back"
                    HorizontalAlignment="Left"/>

I've tried to override GoBack() in my controller but this method is never called.

Then I tried to override GoBack(object parameter, Dictionary<string, object> viewBag) and this time the method is called. So I could symply do 

        public override void GoBack(object parameter, Dictionary<string, object> viewBag)
        {
            viewBag = new Dictionary<string, object>();
            viewBag.Add("Name", "Luca");

            base.GoBack("Luca", viewBag);
        }

I wonder if this is the proper way to pass Parameter and ViewBack back to a controller or if there is a better solution.

**Comment by michaelscodingspot** [comment]
Hi Luca,

Great question.

There are several solutions to this, all work and you can use whatever fits you:

1. You can use **GoBackCommand** in **UseCommandParameter**, and override the other overload of **GoBack** (which you did). This is perfectly fine.

The first overload with no parameters is the one called in **SaveParameterInstance** mode.

2. When using **GoBackCommand** in **SaveParameterInstance** mode, both the **NavigationParameter** and **ViewBag** are taken from history. If you want to prevent memory leaks, you can always pass the **NavigationParameter** as null. Note that if your ViewBag's values are complex objects, it can also cause memory leaks.

3. 
Another option, somewhat less convenient is to derive from GoBackCommand and populate the ViewBag in code:
```
public class MyCommand : MVVMC.GoBackCommand
{
    public MyCommand()
    {
        ViewBag = new Dictionary<string, object>();
        ViewBag["aa"] = "bbb";
    }
}
```
Then, use it in **UseCommandParameter** mode (default)like this:
```
<Button Command="{local:MyCommand ControllerID='Main'}">Back</Button>
```

A better solution would be to make `ViewBack` a dependencyObject, so it can be binded to, but I had trouble implementing this.

Hope this helps,
Michael

**Comment by LucaFagan** [comment]
Hi Michael, 
I'll try the other two solutions you have proposed.

Thanks again for this library, this is the better solution I've found for managing navigation.

Regards
Luca

**Comment by michaelscodingspot** [comment]
Thanks, 
Suffering from existing navigation solutions led me to create this library:)
